name: AWS IAM Identity Center Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggers

jobs:
  use-iam-identity-center:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Install AWS CLI and AWS SSO Login Tool
    - name: Install AWS CLI
      run: |
        sudo apt-get update && sudo apt-get install -y awscli
        aws --version

    # Step 3: Authenticate with AWS environment variables
    - name: AWS Login
      env:
        AWS_REGION: "us-west-1"
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY)
        AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}
        AWS_SSO_START_URL: ${{ secrets.AWS_SSO_START_URL }}  # Your Identity Center Start URL
        AWS_SSO_ACCOUNT_ID: ${{ secrets.AWS_SSO_ACCOUNT_ID }}  # Target account ID
        AWS_SSO_ROLE_NAME: ${{ secrets.AWS_SSO_ROLE_NAME }}  # IAM role in the target account
  
      run: |
        aws sts get-caller-identity
        aws s3 ls  # Example command
