name: Cloud Formation Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggers

jobs:
  use-aws-credentials:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout Code
      uses: actions/checkout@v2

    # Step 2: Install AWS CLI and AWS SSO Login Tool
    - name: Install AWS CLI
      run: |
        sudo apt-get update && sudo apt-get install -y awscli
        aws --version
    # Step 3: Authenticate with AWS environment variables
    - name: AWS Login
      env:
        AWS_REGION: "us-west-1"
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}  
      run: |
        export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
        export AWS_REGION=${AWS_REGION}
        TEMPLATE_BODY="file://cloudformation/resume_cf.yaml"
        TEMPLATE_FILE=cloudformation/resume_cf.yaml
        STACK_NAME='my-resume-cf-stack'
        # Verify caller has the right credentials
        #aws sts get-caller-identity
        
        
        # Validate Cloud Formation template 
        #aws cloudformation validate-template \
        #--template-body $TEMPLATE_BODY \
        #--region $AWS_REGION
        #echo "Template validated"
        #aws cloudformation describe-stacks
        # Deploy Cloud Formation template 
        aws cloudformation deploy\
        --stack-name my-resume-cf-stack\
        --template-file cloudformation/resume_cf.yaml \
        --capabilities CAPABILITY_IAM 
        --debug
        
        # Collect API outputs
        GET_API_URL='aws cloudformation describe-stacks --stack-name $STACK_NAME\
          --query "Stacks[0].Outputs.GetApiUrl"'
        POST_API_URL=aws cloudformation describe-stacks --stack-name $STACK_NAME\
          --query "Stacks[0].Outputs.PostApiUrl"'
      #Step4: Set up Node.js
    - name: set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run Cypress test 
      run: npx cypress run
        
